import { z } from "zod";
export declare const ProjectCreateSchema: z.ZodObject<{
    projectName: z.ZodString;
    clientName: z.ZodOptional<z.ZodString>;
    projectType: z.ZodEnum<["residential", "commercial", "industrial", "renovation", "addition", "other"]>;
    cityId: z.ZodString;
    location: z.ZodString;
    plotArea: z.ZodNumber;
    plotUnit: z.ZodEnum<["marla", "kanal", "sqft", "sqyd", "sqm"]>;
    marlaStandardId: z.ZodDefault<z.ZodString>;
    coveredArea: z.ZodNumber;
    coveredAreaUnit: z.ZodEnum<["sqft", "sqm"]>;
    numberOfFloors: z.ZodNumber;
    hasBasement: z.ZodDefault<z.ZodBoolean>;
    hasGroundFloor: z.ZodDefault<z.ZodBoolean>;
    hasRoof: z.ZodDefault<z.ZodBoolean>;
    constructionQuality: z.ZodDefault<z.ZodEnum<["economy", "standard", "premium", "luxury", "custom"]>>;
    totalBudget: z.ZodOptional<z.ZodNumber>;
    startDate: z.ZodOptional<z.ZodString>;
    expectedCompletion: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    projectName: string;
    projectType: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other";
    cityId: string;
    location: string;
    plotArea: number;
    plotUnit: "marla" | "kanal" | "sqft" | "sqyd" | "sqm";
    marlaStandardId: string;
    coveredArea: number;
    coveredAreaUnit: "sqft" | "sqm";
    numberOfFloors: number;
    hasBasement: boolean;
    hasGroundFloor: boolean;
    hasRoof: boolean;
    constructionQuality: "custom" | "economy" | "standard" | "premium" | "luxury";
    clientName?: string | undefined;
    totalBudget?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    notes?: string | undefined;
}, {
    projectName: string;
    projectType: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other";
    cityId: string;
    location: string;
    plotArea: number;
    plotUnit: "marla" | "kanal" | "sqft" | "sqyd" | "sqm";
    coveredArea: number;
    coveredAreaUnit: "sqft" | "sqm";
    numberOfFloors: number;
    clientName?: string | undefined;
    marlaStandardId?: string | undefined;
    hasBasement?: boolean | undefined;
    hasGroundFloor?: boolean | undefined;
    hasRoof?: boolean | undefined;
    constructionQuality?: "custom" | "economy" | "standard" | "premium" | "luxury" | undefined;
    totalBudget?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    notes?: string | undefined;
}>;
export type ProjectCreateInput = z.infer<typeof ProjectCreateSchema>;
