import { z } from "zod";
export declare const ProjectCreateSchema: z.ZodObject<{
    projectName: z.ZodString;
    clientName: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    clientContact: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    clientWhatsApp: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    referenceNumber: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    projectType: z.ZodDefault<z.ZodEnum<["residential", "commercial", "industrial", "renovation", "addition", "other"]>>;
    cityId: z.ZodString;
    location: z.ZodString;
    society: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    plotArea: z.ZodNumber;
    plotUnit: z.ZodDefault<z.ZodEnum<["marla", "kanal", "sqft", "sqyd", "sqm"]>>;
    marlaStandardId: z.ZodDefault<z.ZodString>;
    plotFront: z.ZodOptional<z.ZodNumber>;
    plotDepth: z.ZodOptional<z.ZodNumber>;
    coveredArea: z.ZodNumber;
    coveredAreaUnit: z.ZodDefault<z.ZodEnum<["sqft", "sqm"]>>;
    numberOfFloors: z.ZodDefault<z.ZodNumber>;
    hasBasement: z.ZodDefault<z.ZodBoolean>;
    hasGroundFloor: z.ZodDefault<z.ZodBoolean>;
    hasRoof: z.ZodDefault<z.ZodBoolean>;
    constructionQuality: z.ZodDefault<z.ZodEnum<["economy", "standard", "premium", "luxury", "custom"]>>;
    buildingHeight: z.ZodOptional<z.ZodNumber>;
    plinthHeight: z.ZodOptional<z.ZodNumber>;
    floorToFloorHeight: z.ZodOptional<z.ZodNumber>;
    clearCeilingHeight: z.ZodOptional<z.ZodNumber>;
    wallHeight: z.ZodOptional<z.ZodNumber>;
    foundationDepth: z.ZodOptional<z.ZodNumber>;
    slabThickness: z.ZodOptional<z.ZodNumber>;
    totalBudget: z.ZodDefault<z.ZodOptional<z.ZodNumber>>;
    startDate: z.ZodOptional<z.ZodString>;
    expectedCompletion: z.ZodOptional<z.ZodString>;
    notes: z.ZodDefault<z.ZodOptional<z.ZodString>>;
    projectImageUrl: z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodLiteral<"">]>>;
    status: z.ZodDefault<z.ZodEnum<["planning", "active", "estimating", "quotation", "approved", "under_construction", "completed", "on_hold", "archived"]>>;
}, "strip", z.ZodTypeAny, {
    status: "planning" | "active" | "estimating" | "quotation" | "approved" | "under_construction" | "completed" | "on_hold" | "archived";
    projectName: string;
    clientName: string;
    clientContact: string;
    clientWhatsApp: string;
    referenceNumber: string;
    projectType: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other";
    cityId: string;
    location: string;
    society: string;
    plotArea: number;
    plotUnit: "marla" | "kanal" | "sqft" | "sqyd" | "sqm";
    marlaStandardId: string;
    coveredArea: number;
    coveredAreaUnit: "sqft" | "sqm";
    numberOfFloors: number;
    hasBasement: boolean;
    hasGroundFloor: boolean;
    hasRoof: boolean;
    constructionQuality: "custom" | "economy" | "standard" | "premium" | "luxury";
    totalBudget: number;
    notes: string;
    plotFront?: number | undefined;
    plotDepth?: number | undefined;
    buildingHeight?: number | undefined;
    plinthHeight?: number | undefined;
    floorToFloorHeight?: number | undefined;
    clearCeilingHeight?: number | undefined;
    wallHeight?: number | undefined;
    foundationDepth?: number | undefined;
    slabThickness?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    projectImageUrl?: string | undefined;
}, {
    projectName: string;
    cityId: string;
    location: string;
    plotArea: number;
    coveredArea: number;
    status?: "planning" | "active" | "estimating" | "quotation" | "approved" | "under_construction" | "completed" | "on_hold" | "archived" | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientWhatsApp?: string | undefined;
    referenceNumber?: string | undefined;
    projectType?: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other" | undefined;
    society?: string | undefined;
    plotUnit?: "marla" | "kanal" | "sqft" | "sqyd" | "sqm" | undefined;
    marlaStandardId?: string | undefined;
    plotFront?: number | undefined;
    plotDepth?: number | undefined;
    coveredAreaUnit?: "sqft" | "sqm" | undefined;
    numberOfFloors?: number | undefined;
    hasBasement?: boolean | undefined;
    hasGroundFloor?: boolean | undefined;
    hasRoof?: boolean | undefined;
    constructionQuality?: "custom" | "economy" | "standard" | "premium" | "luxury" | undefined;
    buildingHeight?: number | undefined;
    plinthHeight?: number | undefined;
    floorToFloorHeight?: number | undefined;
    clearCeilingHeight?: number | undefined;
    wallHeight?: number | undefined;
    foundationDepth?: number | undefined;
    slabThickness?: number | undefined;
    totalBudget?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    notes?: string | undefined;
    projectImageUrl?: string | undefined;
}>;
export declare const ProjectUpdateSchema: z.ZodObject<{
    projectName: z.ZodOptional<z.ZodString>;
    clientName: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    clientContact: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    clientWhatsApp: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    referenceNumber: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    projectType: z.ZodOptional<z.ZodDefault<z.ZodEnum<["residential", "commercial", "industrial", "renovation", "addition", "other"]>>>;
    cityId: z.ZodOptional<z.ZodString>;
    location: z.ZodOptional<z.ZodString>;
    society: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    plotArea: z.ZodOptional<z.ZodNumber>;
    plotUnit: z.ZodOptional<z.ZodDefault<z.ZodEnum<["marla", "kanal", "sqft", "sqyd", "sqm"]>>>;
    marlaStandardId: z.ZodOptional<z.ZodDefault<z.ZodString>>;
    plotFront: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    plotDepth: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    coveredArea: z.ZodOptional<z.ZodNumber>;
    coveredAreaUnit: z.ZodOptional<z.ZodDefault<z.ZodEnum<["sqft", "sqm"]>>>;
    numberOfFloors: z.ZodOptional<z.ZodDefault<z.ZodNumber>>;
    hasBasement: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    hasGroundFloor: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    hasRoof: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    constructionQuality: z.ZodOptional<z.ZodDefault<z.ZodEnum<["economy", "standard", "premium", "luxury", "custom"]>>>;
    buildingHeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    plinthHeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    floorToFloorHeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    clearCeilingHeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    wallHeight: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    foundationDepth: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    slabThickness: z.ZodOptional<z.ZodOptional<z.ZodNumber>>;
    totalBudget: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodNumber>>>;
    startDate: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    expectedCompletion: z.ZodOptional<z.ZodOptional<z.ZodString>>;
    notes: z.ZodOptional<z.ZodDefault<z.ZodOptional<z.ZodString>>>;
    projectImageUrl: z.ZodOptional<z.ZodOptional<z.ZodUnion<[z.ZodString, z.ZodLiteral<"">]>>>;
    status: z.ZodOptional<z.ZodDefault<z.ZodEnum<["planning", "active", "estimating", "quotation", "approved", "under_construction", "completed", "on_hold", "archived"]>>>;
}, "strip", z.ZodTypeAny, {
    status?: "planning" | "active" | "estimating" | "quotation" | "approved" | "under_construction" | "completed" | "on_hold" | "archived" | undefined;
    projectName?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientWhatsApp?: string | undefined;
    referenceNumber?: string | undefined;
    projectType?: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other" | undefined;
    cityId?: string | undefined;
    location?: string | undefined;
    society?: string | undefined;
    plotArea?: number | undefined;
    plotUnit?: "marla" | "kanal" | "sqft" | "sqyd" | "sqm" | undefined;
    marlaStandardId?: string | undefined;
    plotFront?: number | undefined;
    plotDepth?: number | undefined;
    coveredArea?: number | undefined;
    coveredAreaUnit?: "sqft" | "sqm" | undefined;
    numberOfFloors?: number | undefined;
    hasBasement?: boolean | undefined;
    hasGroundFloor?: boolean | undefined;
    hasRoof?: boolean | undefined;
    constructionQuality?: "custom" | "economy" | "standard" | "premium" | "luxury" | undefined;
    buildingHeight?: number | undefined;
    plinthHeight?: number | undefined;
    floorToFloorHeight?: number | undefined;
    clearCeilingHeight?: number | undefined;
    wallHeight?: number | undefined;
    foundationDepth?: number | undefined;
    slabThickness?: number | undefined;
    totalBudget?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    notes?: string | undefined;
    projectImageUrl?: string | undefined;
}, {
    status?: "planning" | "active" | "estimating" | "quotation" | "approved" | "under_construction" | "completed" | "on_hold" | "archived" | undefined;
    projectName?: string | undefined;
    clientName?: string | undefined;
    clientContact?: string | undefined;
    clientWhatsApp?: string | undefined;
    referenceNumber?: string | undefined;
    projectType?: "residential" | "commercial" | "industrial" | "renovation" | "addition" | "other" | undefined;
    cityId?: string | undefined;
    location?: string | undefined;
    society?: string | undefined;
    plotArea?: number | undefined;
    plotUnit?: "marla" | "kanal" | "sqft" | "sqyd" | "sqm" | undefined;
    marlaStandardId?: string | undefined;
    plotFront?: number | undefined;
    plotDepth?: number | undefined;
    coveredArea?: number | undefined;
    coveredAreaUnit?: "sqft" | "sqm" | undefined;
    numberOfFloors?: number | undefined;
    hasBasement?: boolean | undefined;
    hasGroundFloor?: boolean | undefined;
    hasRoof?: boolean | undefined;
    constructionQuality?: "custom" | "economy" | "standard" | "premium" | "luxury" | undefined;
    buildingHeight?: number | undefined;
    plinthHeight?: number | undefined;
    floorToFloorHeight?: number | undefined;
    clearCeilingHeight?: number | undefined;
    wallHeight?: number | undefined;
    foundationDepth?: number | undefined;
    slabThickness?: number | undefined;
    totalBudget?: number | undefined;
    startDate?: string | undefined;
    expectedCompletion?: string | undefined;
    notes?: string | undefined;
    projectImageUrl?: string | undefined;
}>;
export type ProjectCreateInput = z.infer<typeof ProjectCreateSchema>;
export type ProjectUpdateInput = z.infer<typeof ProjectUpdateSchema>;
