packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - core-js
  - esbuild

ignoredBuiltDependencies:
  - unrs-resolver

allowBuilds:
  core-js: true
  esbuild: true
  unrs-resolver: false
