import { MaterialRate, LabourRate, Project } from "@buildcost/types";

export const INITIAL_MATERIAL_RATES: MaterialRate[] = [
  {
    id: "rate_cement_isb",
    materialId: "mat_cement",
    materialName: "Cement (OPC)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Bestway Cement",
    grade: "OPC 50kg",
    unit: "bag",
    baseRate: 1420,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1450,
    currency: "PKR",
    sourceId: "src_isb",
    sourceName: "Islamabad Market Survey",
    sourceType: "market_survey",
    verifiedAt: "2 hours ago",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 2.5,
    isDemoSample: true
  },
  {
    id: "rate_steel_isb",
    materialId: "mat_steel_g60",
    materialName: "Steel (Grade 60)",
    categoryKey: "structural",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Mughal Steel",
    grade: "Grade 60 Billet",
    unit: "ton",
    baseRate: 255000,
    transportRate: 3000,
    loadingRate: 1000,
    unloadingRate: 1000,
    deliveredRate: 260000,
    currency: "PKR",
    sourceId: "src_isb",
    sourceName: "I-9 Industrial Survey",
    sourceType: "market_survey",
    verifiedAt: "3 hours ago",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: -1.1,
    isDemoSample: true
  },
  {
    id: "rate_sand_isb",
    materialId: "mat_sand_chenab",
    materialName: "Sand (Chenab)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "River Bed",
    grade: "Medium Washed",
    unit: "cft",
    baseRate: 42,
    transportRate: 2,
    loadingRate: 0.5,
    unloadingRate: 0.5,
    deliveredRate: 45,
    currency: "PKR",
    sourceId: "src_isb",
    sourceName: "Rawalpindi Mandi",
    sourceType: "market_survey",
    verifiedAt: "Today",
    confidenceScore: "MEDIUM",
    status: "verified",
    trendPercentage: 0.5,
    isDemoSample: true
  },
  {
    id: "rate_crush_isb",
    materialId: "mat_crush_margalla",
    materialName: "Crush (Bajri)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Margalla Quarry",
    grade: '1/2" Graded',
    unit: "cft",
    baseRate: 62,
    transportRate: 2,
    loadingRate: 0.5,
    unloadingRate: 0.5,
    deliveredRate: 65,
    currency: "PKR",
    sourceId: "src_isb",
    sourceName: "Margalla Plant Survey",
    sourceType: "market_survey",
    verifiedAt: "Yesterday",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: true
  },
  {
    id: "rate_bricks_isb",
    materialId: "mat_brick_awwal",
    materialName: "Bricks (Awwal)",
    categoryKey: "masonry",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Rawat Bhatta",
    grade: "Red Clay A-Grade",
    unit: "piece",
    baseRate: 13.5,
    transportRate: 0.4,
    loadingRate: 0.05,
    unloadingRate: 0.05,
    deliveredRate: 14.0,
    currency: "PKR",
    sourceId: "src_isb",
    sourceName: "Rawat Bhatta Association",
    sourceType: "supplier",
    verifiedAt: "1 day ago",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.8,
    isDemoSample: true
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj_buildify_tower",
    userId: "usr_demo",
    projectName: "Buildify Tower",
    clientName: "Umer Sheikh",
    projectType: "commercial",
    cityId: "isb",
    location: "Central Business District, Islamabad",
    plotArea: 15500,
    plotUnit: "sqft",
    marlaStandardId: "marla_225",
    coveredArea: 15500,
    coveredAreaUnit: "sqft",
    numberOfFloors: 13, // G+12
    hasBasement: true,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "premium",
    totalBudget: 75000000,
    status: "estimating",
    createdAt: "2026-08-15",
    updatedAt: "2026-09-04"
  },
  {
    id: "proj_f10_residence",
    userId: "usr_demo",
    projectName: "F-10 Executive Villa",
    clientName: "Dr. Tariq Mahmood",
    projectType: "residential",
    cityId: "isb",
    location: "Sector F-10/2, Islamabad",
    plotArea: 500,
    plotUnit: "sqyd",
    marlaStandardId: "marla_225",
    coveredArea: 5500,
    coveredAreaUnit: "sqft",
    numberOfFloors: 2,
    hasBasement: false,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "luxury",
    totalBudget: 28000000,
    status: "under_construction",
    createdAt: "2026-08-01",
    updatedAt: "2026-09-02"
  },
  {
    id: "proj_dha_phase5",
    userId: "usr_demo",
    projectName: "DHA Phase 5 Duplex",
    clientName: "Salman Khan",
    projectType: "residential",
    cityId: "lhe",
    location: "Sector C, DHA Phase 5, Lahore",
    plotArea: 10,
    plotUnit: "marla",
    marlaStandardId: "marla_225",
    coveredArea: 3800,
    coveredAreaUnit: "sqft",
    numberOfFloors: 2,
    hasBasement: false,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "standard",
    totalBudget: 15000000,
    status: "planning",
    createdAt: "2026-08-20",
    updatedAt: "2026-09-03"
  }
];

export const INITIAL_LABOUR_RATES: LabourRate[] = [
  {
    id: "lab_mason",
    role: "Head Mason (Raj Mistry)",
    roleUrdu: "راج مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "supervisor",
    pricingType: "per_day",
    rate: 2800,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_worker",
    role: "Mason (Raj Mazdoor)",
    roleUrdu: "مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_helper",
    role: "Labourer / Helper (Mazdoor)",
    roleUrdu: "مزدور",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "helper",
    pricingType: "per_day",
    rate: 1500,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_steel",
    role: "Steel Fixer (Bar Bender)",
    roleUrdu: "سریا باندھنے والا",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2500,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_plumber",
    role: "Plumber",
    roleUrdu: "پلمبر",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_electrician",
    role: "Electrician",
    roleUrdu: "الیکٹریشن",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_tiles",
    role: "Tile Worker",
    roleUrdu: "ٹائل مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_sqft",
    rate: 45,
    currency: "PKR",
    sourceName: "Contractor Rate Schedule",
    verifiedAt: "Today"
  },
  {
    id: "lab_painter",
    role: "Painter",
    roleUrdu: "پینٹر",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_sqft",
    rate: 20,
    currency: "PKR",
    sourceName: "Contractor Rate Schedule",
    verifiedAt: "Today"
  }
];
