import {
  MaterialRate,
  LabourRate,
  Project,
  CalculatorTemplate,
  MaterialWatchlistItem,
  ProjectChecklistItem,
  CalculationSnapshot,
  EstimateVersion,
  ShareLink
} from "@buildcost/types";

export const INITIAL_MATERIAL_RATES: MaterialRate[] = [
  // 1. CEMENT
  {
    id: "rate_cement_isb",
    materialId: "mat_cement",
    materialName: "Portland Cement (50kg Bag)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Bestway Cement / Fauji",
    grade: "OPC 50kg (Type 1)",
    unit: "bag",
    baseRate: 1420,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1450,
    currency: "PKR",
    sourceId: "src_apcma",
    sourceName: "All Pakistan Cement Manufacturers Association (APCMA) / PBS",
    sourceType: "official",
    verifiedAt: "Today 09:30 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 2.5,
    isDemoSample: false
  },
  {
    id: "rate_cement_lhe",
    materialId: "mat_cement",
    materialName: "Portland Cement (50kg Bag)",
    categoryKey: "civil",
    cityId: "lhe",
    cityName: "Lahore",
    brand: "Maple Leaf / Pioneer",
    grade: "OPC 50kg (Type 1)",
    unit: "bag",
    baseRate: 1390,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1420,
    currency: "PKR",
    sourceId: "src_apcma",
    sourceName: "APCMA Dealer Price Index",
    sourceType: "official",
    verifiedAt: "Today 10:00 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.8,
    isDemoSample: false
  },
  {
    id: "rate_cement_khi",
    materialId: "mat_cement",
    materialName: "Portland Cement (50kg Bag)",
    categoryKey: "civil",
    cityId: "khi",
    cityName: "Karachi",
    brand: "Lucky Cement / Falcon",
    grade: "OPC 50kg (Type 1)",
    unit: "bag",
    baseRate: 1370,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1400,
    currency: "PKR",
    sourceId: "src_apcma",
    sourceName: "Karachi Shershah Wholesalers & PBS",
    sourceType: "official",
    verifiedAt: "Today 09:00 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.5,
    isDemoSample: false
  },

  // 2. STEEL / REBAR
  {
    id: "rate_steel_isb",
    materialId: "mat_steel_g60",
    materialName: "Deformed Steel Bar Grade 60",
    categoryKey: "structural",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Mughal Steel / Ittehad",
    grade: "ASTM A615 Grade 60 Prime Billet",
    unit: "ton",
    baseRate: 255000,
    transportRate: 3000,
    loadingRate: 1000,
    unloadingRate: 1000,
    deliveredRate: 260000,
    currency: "PKR",
    sourceId: "src_psrma",
    sourceName: "Pakistan Steel Re-Rolling Mills Association (PSRMA)",
    sourceType: "official",
    verifiedAt: "Today 11:15 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: -1.1,
    isDemoSample: false
  },
  {
    id: "rate_steel_lhe",
    materialId: "mat_steel_g60",
    materialName: "Deformed Steel Bar Grade 60",
    categoryKey: "structural",
    cityId: "lhe",
    cityName: "Lahore",
    brand: "Mughal / AFCO Steel",
    grade: "ASTM A615 Grade 60 Prime Billet",
    unit: "ton",
    baseRate: 252000,
    transportRate: 3000,
    loadingRate: 1000,
    unloadingRate: 1000,
    deliveredRate: 257000,
    currency: "PKR",
    sourceId: "src_psrma",
    sourceName: "Badami Bagh Wholesale Market Daily Bulletin",
    sourceType: "market_survey",
    verifiedAt: "Today 10:45 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: -0.8,
    isDemoSample: false
  },
  {
    id: "rate_steel_khi",
    materialId: "mat_steel_g60",
    materialName: "Deformed Steel Bar Grade 60",
    categoryKey: "structural",
    cityId: "khi",
    cityName: "Karachi",
    brand: "Amreli Steels / Agha",
    grade: "ASTM A615 Grade 60 Prime Billet",
    unit: "ton",
    baseRate: 256000,
    transportRate: 2000,
    loadingRate: 1000,
    unloadingRate: 1000,
    deliveredRate: 260000,
    currency: "PKR",
    sourceId: "src_psrma",
    sourceName: "PSRMA Southern Chapter & Shershah",
    sourceType: "official",
    verifiedAt: "Today 10:30 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 3. BRICKS & BLOCKS
  {
    id: "rate_bricks_isb",
    materialId: "mat_brick_awwal",
    materialName: "Red Clay Bricks (Awwal / A-Grade)",
    categoryKey: "masonry",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Rawat Kilns",
    grade: "First Class Kiln-Fired 9x4.5x3 in",
    unit: "piece",
    baseRate: 13.5,
    transportRate: 0.4,
    loadingRate: 0.05,
    unloadingRate: 0.05,
    deliveredRate: 14.0,
    currency: "PKR",
    sourceId: "src_kiln",
    sourceName: "Rawat & Chakbeli Bhatta Association Schedule",
    sourceType: "supplier",
    verifiedAt: "Yesterday 04:00 PM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.8,
    isDemoSample: false
  },
  {
    id: "rate_concrete_block_isb",
    materialId: "mat_concrete_block",
    materialName: "Solid Concrete Masonry Block (8x8x16 in)",
    categoryKey: "masonry",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "National Pavers / Izhar",
    grade: "Compressive Strength > 1500 PSI",
    unit: "piece",
    baseRate: 85,
    transportRate: 3,
    loadingRate: 1,
    unloadingRate: 1,
    deliveredRate: 90,
    currency: "PKR",
    sourceId: "src_mfg",
    sourceName: "Izhar Concrete Plant Direct Dispatch",
    sourceType: "supplier",
    verifiedAt: "2 days ago",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 4. SAND & AGGREGATE (CRUSH)
  {
    id: "rate_sand_isb",
    materialId: "mat_sand_chenab",
    materialName: "Chenab River Sand (Medium Coarse)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "River Bed Mining",
    grade: "Washed & Screened River Bed",
    unit: "cft",
    baseRate: 42,
    transportRate: 2,
    loadingRate: 0.5,
    unloadingRate: 0.5,
    deliveredRate: 45,
    currency: "PKR",
    sourceId: "src_mandi",
    sourceName: "Rawalpindi Pirwadhai Truck Mandi Field Survey",
    sourceType: "market_survey",
    verifiedAt: "Today 08:00 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.5,
    isDemoSample: false
  },
  {
    id: "rate_crush_isb",
    materialId: "mat_crush_margalla",
    materialName: "Margalla Hills Crush (Bajri 1/2 in)",
    categoryKey: "civil",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Margalla Quarry",
    grade: "Angular Limestone 1/2 to 3/4 in",
    unit: "cft",
    baseRate: 62,
    transportRate: 2,
    loadingRate: 0.5,
    unloadingRate: 0.5,
    deliveredRate: 65,
    currency: "PKR",
    sourceId: "src_quarry",
    sourceName: "Margalla Stone Crushers Association",
    sourceType: "official",
    verifiedAt: "Today 08:30 AM PKT",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 5. TILES & FLOORING
  {
    id: "rate_tiles_porcelain_isb",
    materialId: "mat_tiles_porcelain",
    materialName: "Porcelain Floor Tiles 60x60 cm (24x24 in)",
    categoryKey: "flooring",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Master Ceramics / Shabbir Stile",
    grade: "Grade 1 Polished Vitrified",
    unit: "sqft",
    baseRate: 175,
    transportRate: 3,
    loadingRate: 1,
    unloadingRate: 1,
    deliveredRate: 180,
    currency: "PKR",
    sourceId: "src_tiles",
    sourceName: "Master Ceramics I-9 Company Showroom Price List",
    sourceType: "supplier",
    verifiedAt: "This Week",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.2,
    isDemoSample: false
  },
  {
    id: "rate_tile_bond_isb",
    materialId: "mat_tile_bond",
    materialName: "Polymer Modified Tile Bond (20kg Bag)",
    categoryKey: "flooring",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Stile Bond / Master Bond",
    grade: "Heavy Duty Waterproof Adhesive",
    unit: "bag",
    baseRate: 720,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 750,
    currency: "PKR",
    sourceId: "src_tiles",
    sourceName: "Authorized Stile Chemical Depot",
    sourceType: "supplier",
    verifiedAt: "This Week",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 6. PAINTS & COATINGS
  {
    id: "rate_paint_matt_isb",
    materialId: "mat_paint_matt",
    materialName: "Interior Matt Enamel Paint (16 Litre Drum)",
    categoryKey: "paint",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Dulux Velvet Touch / Berger",
    grade: "Premium Washable Interior Emulsion",
    unit: "litre",
    baseRate: 830,
    transportRate: 10,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 850,
    currency: "PKR",
    sourceId: "src_dulux",
    sourceName: "AkzoNobel Dulux Pakistan Wholesale Price List",
    sourceType: "official",
    verifiedAt: "Sep 1, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 2.0,
    isDemoSample: false
  },
  {
    id: "rate_weather_coat_isb",
    materialId: "mat_weather_coat",
    materialName: "Exterior WeatherCoat Paint (16 Litre Drum)",
    categoryKey: "paint",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Berger WeatherCoat / Brighto",
    grade: "UV Resistant Elastomeric Exterior",
    unit: "litre",
    baseRate: 980,
    transportRate: 10,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1000,
    currency: "PKR",
    sourceId: "src_berger",
    sourceName: "Berger Paints Pakistan Commercial Rate Schedule",
    sourceType: "official",
    verifiedAt: "Sep 1, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.5,
    isDemoSample: false
  },

  // 7. PLUMBING & PIPES
  {
    id: "rate_pprc_pipe_isb",
    materialId: "mat_pprc_pipe",
    materialName: "PPRC Water Pipe 25mm 1-inch (4m Length)",
    categoryKey: "plumbing",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Master PPRC / Popular / Turk Plast",
    grade: "PN-20 Hot & Cold Water DIN 8077",
    unit: "piece",
    baseRate: 640,
    transportRate: 15,
    loadingRate: 2,
    unloadingRate: 3,
    deliveredRate: 660,
    currency: "PKR",
    sourceId: "src_pprc",
    sourceName: "Master Pipes Authorized Wholesale Distribution Hub",
    sourceType: "supplier",
    verifiedAt: "Aug 30, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },
  {
    id: "rate_pvc_drainage_isb",
    materialId: "mat_pvc_drainage",
    materialName: "uPVC Soil & Waste Pipe 4-inch (10ft Length)",
    categoryKey: "plumbing",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "IIL / Popular Pipes",
    grade: "Class B BS 3505 Heavy Wall",
    unit: "piece",
    baseRate: 1420,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 1450,
    currency: "PKR",
    sourceId: "src_iil",
    sourceName: "International Industries Limited (IIL) Price Bulletin",
    sourceType: "official",
    verifiedAt: "Aug 28, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: -0.5,
    isDemoSample: false
  },

  // 8. ELECTRICAL
  {
    id: "rate_cable_729_isb",
    materialId: "mat_cable_729",
    materialName: "Copper Electric Cable 7/0.029 (90m Coil)",
    categoryKey: "electrical",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Pakistan Cables / Fast Cables",
    grade: "99.99% Pure Copper 450/750V BS 6004",
    unit: "piece",
    baseRate: 26800,
    transportRate: 100,
    loadingRate: 50,
    unloadingRate: 50,
    deliveredRate: 27000,
    currency: "PKR",
    sourceId: "src_pak_cables",
    sourceName: "Pakistan Cables Official Distributor Price Sheet",
    sourceType: "official",
    verifiedAt: "Sep 2, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.0,
    isDemoSample: false
  },
  {
    id: "rate_cable_329_isb",
    materialId: "mat_cable_329",
    materialName: "Copper Electric Cable 3/0.029 (90m Coil)",
    categoryKey: "electrical",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Pakistan Cables / Fast Cables",
    grade: "Single Core Pure Copper Lighting Wire",
    unit: "piece",
    baseRate: 12200,
    transportRate: 100,
    loadingRate: 50,
    unloadingRate: 50,
    deliveredRate: 12400,
    currency: "PKR",
    sourceId: "src_pak_cables",
    sourceName: "Pakistan Cables Official Distributor Price Sheet",
    sourceType: "official",
    verifiedAt: "Sep 2, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.0,
    isDemoSample: false
  },

  // 9. WOOD & DOORS
  {
    id: "rate_door_ash_isb",
    materialId: "mat_door_ash",
    materialName: "Semi-Solid Ash Wood Pressed Door (3.5x7 ft)",
    categoryKey: "woodwork",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Interwood / Local Master Craft",
    grade: "Commercial Grade with Ash Veneer Face",
    unit: "piece",
    baseRate: 15500,
    transportRate: 300,
    loadingRate: 100,
    unloadingRate: 100,
    deliveredRate: 16000,
    currency: "PKR",
    sourceId: "src_wood_mkt",
    sourceName: "Golra Road Timber Market Manufacturers Association",
    sourceType: "market_survey",
    verifiedAt: "Aug 25, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 10. SANITARY WARE
  {
    id: "rate_commode_porta_isb",
    materialId: "mat_commode_porta",
    materialName: "One-Piece Ceramic Commode & Seat",
    categoryKey: "sanitary",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Porta / Marcopolo",
    grade: "Vitreous China Dual Flush Water-Saving",
    unit: "piece",
    baseRate: 18500,
    transportRate: 300,
    loadingRate: 100,
    unloadingRate: 100,
    deliveredRate: 19000,
    currency: "PKR",
    sourceId: "src_porta",
    sourceName: "Porta Sanitary Official Dealer Schedule",
    sourceType: "supplier",
    verifiedAt: "Sep 1, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 0.0,
    isDemoSample: false
  },

  // 11. ALUMINIUM & GLASS
  {
    id: "rate_aluminium_window_isb",
    materialId: "mat_aluminium_window",
    materialName: "Aluminium Sliding Window Frame (1.6mm Section)",
    categoryKey: "aluminium",
    cityId: "isb",
    cityName: "Islamabad",
    brand: "Chawla / Prime Aluminium",
    grade: "Powder Coated Champagne/Black with 5mm Tinted Glass",
    unit: "sqft",
    baseRate: 620,
    transportRate: 20,
    loadingRate: 5,
    unloadingRate: 5,
    deliveredRate: 650,
    currency: "PKR",
    sourceId: "src_aluminium",
    sourceName: "Islamabad Glass & Aluminium Fabricators Syndicate",
    sourceType: "market_survey",
    verifiedAt: "Sep 3, 2026",
    confidenceScore: "HIGH",
    status: "verified",
    trendPercentage: 1.5,
    isDemoSample: false
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "proj_buildify_tower",
    userId: "usr_demo",
    projectName: "Buildify Tower",
    clientName: "Umer Sheikh",
    projectType: "commercial",
    cityId: "isb",
    location: "Central Business District, Islamabad",
    plotArea: 15500,
    plotUnit: "sqft",
    marlaStandardId: "marla_225",
    coveredArea: 15500,
    coveredAreaUnit: "sqft",
    numberOfFloors: 13, // G+12
    hasBasement: true,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "premium",
    totalBudget: 75000000,
    status: "estimating",
    createdAt: "2026-08-15",
    updatedAt: "2026-09-04"
  },
  {
    id: "proj_f10_residence",
    userId: "usr_demo",
    projectName: "F-10 Executive Villa",
    clientName: "Dr. Tariq Mahmood",
    projectType: "residential",
    cityId: "isb",
    location: "Sector F-10/2, Islamabad",
    plotArea: 500,
    plotUnit: "sqyd",
    marlaStandardId: "marla_225",
    coveredArea: 5500,
    coveredAreaUnit: "sqft",
    numberOfFloors: 2,
    hasBasement: false,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "luxury",
    totalBudget: 28000000,
    status: "under_construction",
    createdAt: "2026-08-01",
    updatedAt: "2026-09-02"
  },
  {
    id: "proj_dha_phase5",
    userId: "usr_demo",
    projectName: "DHA Phase 5 Duplex",
    clientName: "Salman Khan",
    projectType: "residential",
    cityId: "lhe",
    location: "Sector C, DHA Phase 5, Lahore",
    plotArea: 10,
    plotUnit: "marla",
    marlaStandardId: "marla_225",
    coveredArea: 3800,
    coveredAreaUnit: "sqft",
    numberOfFloors: 2,
    hasBasement: false,
    hasGroundFloor: true,
    hasRoof: true,
    constructionQuality: "standard",
    totalBudget: 15000000,
    status: "planning",
    createdAt: "2026-08-20",
    updatedAt: "2026-09-03"
  }
];

export const INITIAL_LABOUR_RATES: LabourRate[] = [
  {
    id: "lab_mason",
    role: "Head Mason (Raj Mistry)",
    roleUrdu: "راج مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "supervisor",
    pricingType: "per_day",
    rate: 2800,
    currency: "PKR",
    sourceName: "Pirwadhai & G-9 Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_worker",
    role: "Mason (Raj Mazdoor)",
    roleUrdu: "مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_helper",
    role: "Labourer / Helper (Mazdoor)",
    roleUrdu: "مزدور",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "helper",
    pricingType: "per_day",
    rate: 1500,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_steel",
    role: "Steel Fixer (Bar Bender)",
    roleUrdu: "سریا باندھنے والا",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2500,
    currency: "PKR",
    sourceName: "Labour Chowk Survey",
    verifiedAt: "Today"
  },
  {
    id: "lab_plumber",
    role: "Plumber",
    roleUrdu: "پلمبر",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Sanitary Contractors Syndicate",
    verifiedAt: "Today"
  },
  {
    id: "lab_electrician",
    role: "Electrician",
    roleUrdu: "الیکٹریشن",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_day",
    rate: 2400,
    currency: "PKR",
    sourceName: "Licensed Electricians Syndicate",
    verifiedAt: "Today"
  },
  {
    id: "lab_tiles",
    role: "Tile Worker",
    roleUrdu: "ٹائل مستری",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_sqft",
    rate: 45,
    currency: "PKR",
    sourceName: "Contractor Rate Schedule",
    verifiedAt: "Today"
  },
  {
    id: "lab_painter",
    role: "Painter",
    roleUrdu: "پینٹر",
    cityId: "isb",
    cityName: "Islamabad",
    skillLevel: "skilled",
    pricingType: "per_sqft",
    rate: 20,
    currency: "PKR",
    sourceName: "Master Painters Guild",
    verifiedAt: "Today"
  }
];

export const INITIAL_TEMPLATES: CalculatorTemplate[] = [
  {
    id: "tpl_5_marla_double",
    userId: "system",
    title: "5 Marla Double Storey House",
    description: "Typical LDA/CDA residential 5 Marla (225 sqft/marla) with 1,950 sqft covered area (Ground + First + Mumty).",
    calculatorType: "house-estimate",
    plotSize: 5,
    plotUnit: "marla",
    coveredArea: 1950,
    floors: 2,
    constructionQuality: "standard",
    cityId: "lhe",
    inputs: {
      plotArea: 5,
      plotUnit: "marla",
      coveredArea: 1950,
      numberOfFloors: 2,
      constructionQuality: "standard",
      cityId: "lhe"
    },
    isSystemPreset: true,
    createdAt: "2026-08-01"
  },
  {
    id: "tpl_10_marla_luxury",
    userId: "system",
    title: "10 Marla Luxury Residence",
    description: "3,800 sqft covered area, 4 master bedrooms, designer tiles, porcelain washrooms, and imported fittings.",
    calculatorType: "house-estimate",
    plotSize: 10,
    plotUnit: "marla",
    coveredArea: 3800,
    floors: 2,
    constructionQuality: "luxury",
    cityId: "isb",
    inputs: {
      plotArea: 10,
      plotUnit: "marla",
      coveredArea: 3800,
      numberOfFloors: 2,
      constructionQuality: "luxury",
      cityId: "isb"
    },
    isSystemPreset: true,
    createdAt: "2026-08-05"
  },
  {
    id: "tpl_1_kanal_executive",
    userId: "system",
    title: "1 Kanal Executive Villa",
    description: "6,200 sqft covered area with basement, double height lobby, solar structural prep, and premium Grade 60 steel.",
    calculatorType: "house-estimate",
    plotSize: 1,
    plotUnit: "kanal",
    coveredArea: 6200,
    floors: 3,
    constructionQuality: "premium",
    cityId: "isb",
    inputs: {
      plotArea: 1,
      plotUnit: "kanal",
      coveredArea: 6200,
      numberOfFloors: 3,
      constructionQuality: "premium",
      cityId: "isb"
    },
    isSystemPreset: true,
    createdAt: "2026-08-10"
  },
  {
    id: "tpl_office_renovation",
    userId: "system",
    title: "Commercial Office Renovation",
    description: "1,500 sqft interior retrofit: false ceiling, 60x60cm porcelain floor tiles, plastic emulsion paint, and rewiring.",
    calculatorType: "flooring",
    coveredArea: 1500,
    constructionQuality: "standard",
    cityId: "khi",
    inputs: {
      areaSqft: 1500,
      tileType: "porcelain",
      includeSkirting: true
    },
    isSystemPreset: true,
    createdAt: "2026-08-15"
  },
  {
    id: "tpl_boundary_wall",
    userId: "system",
    title: "9-inch Brick Boundary Wall (300 Rft)",
    description: "9-inch thick brickwork with 1:6 cement mortar, DPC layer, and RCC stiffener columns every 10 feet.",
    calculatorType: "brickwork",
    constructionQuality: "standard",
    cityId: "rwp",
    inputs: {
      lengthFeet: 300,
      heightFeet: 8,
      thicknessInches: 9,
      mortarRatio: "1:6"
    },
    isSystemPreset: true,
    createdAt: "2026-08-20"
  }
];

export const INITIAL_CHECKLIST: ProjectChecklistItem[] = [
  {
    id: "chk_1",
    projectId: "proj_g13_plaza",
    stage: "planning",
    title: "CDA / Society Building Plan Approval & Demarcation",
    description: "Architectural drawings sanctioned by local development authority and site demarcation letter obtained.",
    status: "completed",
    sortOrder: 1
  },
  {
    id: "chk_2",
    projectId: "proj_g13_plaza",
    stage: "site_preparation",
    title: "Soil Investigation & Site Clearing",
    description: "Soil boring test conducted for bearing capacity (SBC > 1.25 tsf) and temporary water boring installed.",
    status: "completed",
    sortOrder: 2
  },
  {
    id: "chk_3",
    projectId: "proj_g13_plaza",
    stage: "foundation",
    title: "Raft Excavation, Lean Concrete & Termite Proofing",
    description: "Chemical anti-termite treatment sprayed before 1:4:8 lean concrete sub-base.",
    status: "in_progress",
    sortOrder: 3
  },
  {
    id: "chk_4",
    projectId: "proj_g13_plaza",
    stage: "structure",
    title: "Basement Retaining Walls & Grade 60 Rebar Binding",
    description: "Waterproofing admixture (Sika / Fosroc) added to 1:1.5:3 RCC pour.",
    status: "in_progress",
    sortOrder: 4
  },
  {
    id: "chk_5",
    projectId: "proj_g13_plaza",
    stage: "masonry",
    title: "9-Inch Exterior Awwal Brick Walls & DPC Bitumen Coating",
    description: "First class kiln-fired bricks laid with 1:6 cement sand mortar.",
    status: "not_started",
    sortOrder: 5
  },
  {
    id: "chk_6",
    projectId: "proj_g13_plaza",
    stage: "plaster",
    title: "Internal 1/2-Inch (1:4) & External 3/4-Inch (1:3) Plastering",
    description: "Minimum 14 days curing for all exposed plaster surfaces.",
    status: "not_started",
    sortOrder: 6
  },
  {
    id: "chk_7",
    projectId: "proj_g13_plaza",
    stage: "electrical",
    title: "Conduit Piping & Pakistan Cables 99.9% Copper Wiring",
    description: "Pre-slab and wall groove electrical conduit routing with circuit breaker distribution.",
    status: "not_started",
    sortOrder: 7
  },
  {
    id: "chk_8",
    projectId: "proj_g13_plaza",
    stage: "plumbing",
    title: "PPRC Fresh Water & UPVC Drainage Pressure Testing",
    description: "Hydrostatic pressure test at 10 bar for 24 hours prior to wall concealing.",
    status: "not_started",
    sortOrder: 8
  },
  {
    id: "chk_9",
    projectId: "proj_g13_plaza",
    stage: "flooring",
    title: "Floor Screed & Master/Stile Porcelain Tile Installation",
    description: "Bonding agent adhesive used with tile spacers and matching epoxy grouting.",
    status: "not_started",
    sortOrder: 9
  },
  {
    id: "chk_10",
    projectId: "proj_g13_plaza",
    stage: "paint",
    title: "Putty Priming, Plastic Emulsion & WeatherCoat Exterior",
    description: "Three coats of Berger/Dulux weather-resistant paint on all exterior elevations.",
    status: "not_started",
    sortOrder: 10
  },
  {
    id: "chk_11",
    projectId: "proj_g13_plaza",
    stage: "doors_windows",
    title: "Powder-Coated Aluminum Windows & Solid Ash Wood Doors",
    description: "5mm tempered safety glass with heavy-duty weather stripping and stainless steel handles.",
    status: "not_started",
    sortOrder: 11
  },
  {
    id: "chk_12",
    projectId: "proj_g13_plaza",
    stage: "final_inspection",
    title: "Snag List Resolution & Completion Certificate",
    description: "Final walkthrough with client, electrical load testing, and authority completion filing.",
    status: "not_started",
    sortOrder: 12
  }
];

export const INITIAL_WATCHLIST: MaterialWatchlistItem[] = [
  {
    id: "wtch_cement",
    userId: "usr_demo",
    materialId: "mat_cement",
    cityId: "isb",
    targetAlertRate: 1450,
    alertOnIncrease: true,
    alertOnDecrease: true,
    notifyEmail: true,
    notifyInApp: true,
    createdAt: "2026-08-25"
  },
  {
    id: "wtch_steel",
    userId: "usr_demo",
    materialId: "mat_steel_g60",
    cityId: "isb",
    targetAlertRate: 260000,
    alertOnIncrease: true,
    alertOnDecrease: true,
    notifyEmail: true,
    notifyInApp: true,
    createdAt: "2026-08-25"
  },
  {
    id: "wtch_bricks",
    userId: "usr_demo",
    materialId: "mat_brick_awwal",
    cityId: "lhe",
    targetAlertRate: 14000,
    alertOnIncrease: true,
    alertOnDecrease: false,
    notifyEmail: false,
    notifyInApp: true,
    createdAt: "2026-08-25"
  },
  {
    id: "wtch_sand",
    userId: "usr_demo",
    materialId: "mat_sand_chenab",
    cityId: "lhe",
    targetAlertRate: 48,
    alertOnIncrease: true,
    alertOnDecrease: false,
    notifyEmail: false,
    notifyInApp: true,
    createdAt: "2026-08-25"
  }
];

export const INITIAL_CALCULATIONS: CalculationSnapshot[] = [
  {
    id: "calc_5_marla_sample",
    projectId: "proj_dha_phase5",
    calculatorType: "house-estimate",
    inputs: {
      plotArea: 5,
      plotUnit: "marla",
      coveredArea: 1950,
      numberOfFloors: 2,
      constructionQuality: "standard",
      cityId: "lhe"
    },
    result: {
      materialsCost: 5265000,
      labourCost: 1950000,
      equipmentCost: 200000,
      transportCost: 180000,
      finishingCost: 2100000,
      contingencyCost: 484750,
      otherCost: 0,
      grandTotal: 10179750,
      totalCoveredAreaSqft: 1950,
      costPerSqft: 5220,
      materials: [
        {
          materialId: "mat_cement",
          materialName: "Portland Cement (50kg)",
          category: "Civil",
          rawQuantity: 750,
          wastagePercent: 5,
          wastageQuantity: 38,
          finalQuantity: 788,
          unit: "bags",
          unitRate: 1420,
          cost: 1119000
        },
        {
          materialId: "mat_steel_g60",
          materialName: "Grade 60 Deformed Steel",
          category: "Structural",
          rawQuantity: 6.8,
          wastagePercent: 3,
          wastageQuantity: 0.2,
          finalQuantity: 7.0,
          unit: "tons",
          unitRate: 260000,
          cost: 1820000
        },
        {
          materialId: "mat_brick_awwal",
          materialName: "Awwal Kiln Bricks",
          category: "Masonry",
          rawQuantity: 45000,
          wastagePercent: 5,
          wastageQuantity: 2250,
          finalQuantity: 47250,
          unit: "nos",
          unitRate: 14,
          cost: 661500
        }
      ],
      labour: [
        {
          role: "Civil Grey Structure Labour Contract",
          quantity: 1950,
          unit: "sqft",
          rate: 550,
          cost: 1072500
        },
        {
          role: "Finishing, Tile & Paint Labour Contract",
          quantity: 1950,
          unit: "sqft",
          rate: 450,
          cost: 877500
        }
      ],
      assumptions: [
        { key: "city", label: "City", value: "Lahore" },
        { key: "marla", label: "Marla Standard", value: "225 Sq. Ft." },
        { key: "quality", label: "Quality Grade", value: "Standard Finish" },
        { key: "steel_density", label: "Steel Density", value: "3.6 kg/sqft" }
      ]
    },
    ratesSnapshot: {
      mat_cement: { rate: 1420, source: "APCMA Dealer Price Index", verifiedAt: "Today 10:00 AM PKT" },
      mat_steel_g60: { rate: 260000, source: "PSRMA Mills Ex-Factory", verifiedAt: "Today 09:30 AM PKT" },
      mat_brick_awwal: { rate: 14, source: "Bhatta Kiln Association", verifiedAt: "Today 09:30 AM PKT" }
    },
    createdAt: "2026-08-22T10:30:00Z"
  }
];

export const INITIAL_ESTIMATE_VERSIONS: EstimateVersion[] = [
  {
    id: "ver_1",
    projectId: "proj_dha_phase5",
    versionNumber: 1,
    versionName: "Initial Baseline Estimate (Aug 2026)",
    rateSnapshotDate: "2026-08-22T10:30:00Z",
    summaryData: {
      totalCoveredAreaSqft: 1950,
      grandTotal: 10034750,
      costPerSqft: 5146,
      materialsCost: 5120000,
      labourCost: 1950000,
      finishingCost: 2100000
    },
    ratesSnapshot: {
      mat_cement: { rate: 1390, source: "APCMA", verifiedAt: "2026-08-22" },
      mat_steel_g60: { rate: 255000, source: "PSRMA", verifiedAt: "2026-08-22" }
    },
    deltaAmount: 0,
    deltaPercentage: 0,
    createdAt: "2026-08-22T10:30:00Z"
  },
  {
    id: "ver_2",
    projectId: "proj_dha_phase5",
    versionNumber: 2,
    versionName: "Current Market Adjustment (Sep 2026)",
    rateSnapshotDate: "2026-09-04T12:00:00Z",
    summaryData: {
      totalCoveredAreaSqft: 1950,
      grandTotal: 10179750,
      costPerSqft: 5220,
      materialsCost: 5265000,
      labourCost: 1950000,
      finishingCost: 2100000
    },
    ratesSnapshot: {
      mat_cement: { rate: 1420, source: "APCMA", verifiedAt: "Today" },
      mat_steel_g60: { rate: 260000, source: "PSRMA", verifiedAt: "Today" }
    },
    deltaAmount: 145000,
    deltaPercentage: 1.44,
    createdAt: "2026-09-04T12:00:00Z"
  }
];

export const INITIAL_SHARE_LINKS: ShareLink[] = [
  {
    id: "sh_sample_1",
    userId: "usr_demo",
    projectId: "proj_dha_phase5",
    documentType: "estimate",
    documentId: "calc_5_marla_sample",
    documentData: {
      projectName: "DHA Phase 5 Duplex (5 Marla)",
      city: "Lahore",
      coveredArea: 1950,
      grandTotal: 10179750,
      costPerSqft: 5220
    },
    token: "sh-9f8e7d6c-5b4a-3210-fedc-ba9876543210",
    title: "5 Marla Complete House Estimate — DHA Lahore",
    isActive: true,
    allowDownload: true,
    viewOnly: true,
    expiresAt: null,
    revokedAt: null,
    includeClientName: false,
    includePhone: false,
    includeCompany: true,
    includeProjectAddress: false,
    viewCount: 14,
    downloadCount: 3,
    lastViewedAt: "2026-09-04T14:20:00Z",
    createdAt: "2026-08-25T11:00:00Z",
    updatedAt: "2026-09-04T14:20:00Z"
  }
];
